lib: [
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.a"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.cma"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.cmi"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.cmt"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.cmx"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.cmxa"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.cmxs"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/Grout.re"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/META"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/dune-package"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/lib/Grout/opam"
]
bin: [
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/bin/TestExe"
]
doc: [
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/doc/Grout/LICENSE"
  "/Users/kad/dev/grout/_esy/default/store/b/grout-7054f447/install/default/doc/Grout/README.md"
]
