lib: [
  "_build/install/default/lib/Grout/Grout.a"
  "_build/install/default/lib/Grout/Grout.cma"
  "_build/install/default/lib/Grout/Grout.cmi"
  "_build/install/default/lib/Grout/Grout.cmt"
  "_build/install/default/lib/Grout/Grout.cmx"
  "_build/install/default/lib/Grout/Grout.cmxa"
  "_build/install/default/lib/Grout/Grout.cmxs"
  "_build/install/default/lib/Grout/Grout.re"
  "_build/install/default/lib/Grout/META"
  "_build/install/default/lib/Grout/dune-package"
  "_build/install/default/lib/Grout/opam"
]
bin: [
  "_build/install/default/bin/TestExe"
]
doc: [
  "_build/install/default/doc/Grout/LICENSE"
  "_build/install/default/doc/Grout/README.md"
]
